user_security:
    resource: @FOSUserBundle/Resources/config/routing/security.xml
user_profile:
    resource: @FOSUserBundle/Resources/config/routing/profile.yml
user_registration:
    resource: @FOSUserBundle/Resources/config/routing/registration.yml
user_online:
    resource: @FOSUserBundle/Resources/config/routing/online.yml
user_stats:
    resource: @FOSUserBundle/Resources/config/routing/stats.yml

lichess:
    resource: @LichessBundle/Resources/config/routing.yml
lichess_hook:
    resource: @LichessOpeningBundle/Resources/config/routing.yml
lichess_hook_sync:
    resource: @LichessOpeningBundle/Resources/config/routing_sync.yml
lichess_sync:
    resource: @LichessBundle/Resources/config/routing_sync.yml
lichess_translation:
    resource: @LichessTranslationBundle/Resources/config/routing.yml
    prefix: /translation
#lichess_search:
    #resource: @LichessSearchBundle/Resources/config/routing.yml
    #prefix: /search

forum:
    resource: @LichessForumBundle/Resources/config/routing.yml
    prefix: /forum
forum_category:
    resource: @ForumBundle/Resources/config/routing/category.xml
    prefix: /forum
forum_topic:
    resource: @ForumBundle/Resources/config/routing/topic.xml
    prefix: /forum
forum_post:
    resource: @ForumBundle/Resources/config/routing/post.xml
    prefix: /forum
forum_topic_show_compat:
    pattern:        /forum/{categorySlug}/{slug}/{id}.{_format}
    defaults:       { _controller: forum.controller.topic:showCompatAction, _format: "html", id: "" }
    requirements:   { _method: "get|head", _format: "html|xml", slug: "[-\w]+" }

ornicar_message:
    resource: @OrnicarMessageBundle/Resources/config/routing.xml
    prefix: /inbox

fos_comment:
    resource: @FOSCommentBundle/Resources/config/routing.yml
